# Generated by Django 3.1 on 2020-08-07 19:31

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_profile_default_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='default_picture',
            field=models.ImageField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(base_url='/media/uploads/', location='/Users/briansanchez/sei/unit-3/projects/theSpot/media/uploads/'), upload_to='uploads/'),
        ),
    ]
