# Generated by Django 3.1 on 2020-08-08 21:58

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_auto_20200807_1931'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='default_picture',
            new_name='upload_picture',
        ),
        migrations.AddField(
            model_name='city',
            name='upload_picture',
            field=models.ImageField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(base_url='/media/uploads/', location='/Users/briansanchez/sei/unit-3/projects/theSpot/media/uploads/'), upload_to='uploads/'),
        ),
        migrations.AddField(
            model_name='post',
            name='upload_picture',
            field=models.ImageField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(base_url='/media/uploads/', location='/Users/briansanchez/sei/unit-3/projects/theSpot/media/uploads/'), upload_to='uploads/'),
        ),
    ]
