# Generated by Django 3.1 on 2020-08-09 00:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_auto_20200808_2158'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='city',
            name='picture',
        ),
        migrations.RemoveField(
            model_name='post',
            name='picture',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='profile_picture',
        ),
    ]
