# Generated by Django 3.1 on 2020-08-09 00:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_auto_20200808_1841'),
        ('main_app', '0006_auto_20200809_0031'),
    ]

    operations = [
    ]
