# Generated by Django 3.1 on 2020-08-09 01:03

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_merge_20200809_0048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='upload_picture',
            field=models.ImageField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(base_url='/media/uploads/', location='/Users/larson/sei/projects/projectwayfarer/theSpot/media/uploads/'), upload_to='uploads/'),
        ),
    ]
