# Generated by Django 3.1 on 2020-08-10 05:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0009_auto_20200809_2351'),
        ('main_app', '0009_auto_20200810_0424'),
    ]

    operations = [
    ]
