# Generated by Django 3.1 on 2020-08-10 05:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0010_merge_20200810_0516'),
        ('main_app', '0010_auto_20200810_0445'),
    ]

    operations = [
    ]
